### ISSUE TITLE
open() "/var/tmp/nginx/proxy/6/20/0000000206" failed (13: Permission denied) 

### ISSUE THREAD

**Issue by phdelodder** [linuxserver/docker-letsencrypt-arm64#7]
open() "/var/tmp/nginx/proxy/6/20/0000000206" failed (13: Permission denied) while reading upstream, 

Running on Rock64 DietPi

```yaml
  nginx:
      container_name: "nginx"
      image: lsioarmhf/letsencrypt-aarch64:latest
      volumes:
        - /mnt/dietpi_userdata/docker/config/nginx:/config
      environment:
        - PGID=1002
        - PUID=1001
        - TZ=Europe/Brussels
        - EMAIL=xxx
        - URL=xxx
        - SUBDOMAINS=ha,nas,reader,dyn
        - ONLY_SUBDOMAINS=true
        - VALIDATION=http
        - DHLEVEL=4096
      ports:
        - 80:80
        - 443:443
        - 8090:8090
      restart: always
```

More info: 
* Rights: 
```
drwx------  4 abc abc  4096 Mar 29 22:25 6
```
* PS AUX: 
```
84 root       0:00 nginx: master process /usr/sbin/nginx -c /config/nginx/ng
  486 abc        0:21 nginx: worker process
```
* id abc:
```
root@856e26172406:/$ id abc
uid=1001(abc) gid=1002(abc) groups=1002(abc),1000(users)
```
